<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Partyood.Contracts\Partyood.Contracts.csproj" />
    <ProjectReference Include="..\Partyood.Application\Partyood.Application.csproj" />
    <ProjectReference Include="..\Partyood.Infrastructure\Partyood.Infrastructure.csproj" />
  </ItemGroup>

</Project>
